server:
  port: 8082

spring:
  application:
    name: risk-engine-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: risk-engine-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.riskstream.common
        spring.json.value.default.type: com.riskstream.common.RiskEvent

riskstream:
  kafka:
    events-topic: riskstream.events.raw

management:
  endpoints:
    web:
      exposure:
        include: health,info
